// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mongeral.Provisao.V2.Testes.Aceitacao.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Evento de Altereção de Parametros")]
    [NUnit.Framework.CategoryAttribute("EventoAlteracaoParametros")]
    public partial class EventoDeAlterecaoDeParametrosFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EventoAlteracaoParametros.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Evento de Altereção de Parametros", null, ProgrammingLanguage.CSharp, new string[] {
                        "EventoAlteracaoParametros"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Alteração de Parametros")]
        [NUnit.Framework.CategoryAttribute("igonre")]
        public virtual void AlteracaoDeParametros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alteração de Parametros", new string[] {
                        "igonre"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identificador",
                        "IdExterno",
                        "ItemProdutoId",
                        "DataInicioVigencia",
                        "ClasseRiscoId",
                        "TipoFormaContratacaoId",
                        "TipoRendaId",
                        "IdentificadorNegocio",
                        "InscricaoId",
                        "Matricula",
                        "Periodicidade",
                        "DataNascimento",
                        "Sexo"});
            table1.AddRow(new string[] {
                        "9B2B0228-4D0D-4C23-8B49-01A698857709",
                        "10116682815341371",
                        "153417",
                        "01/01/2016",
                        "0",
                        "1",
                        "1",
                        "245a444f-fc39-4ee1",
                        "101166828534",
                        "100",
                        "30",
                        "01/01/1980",
                        "Masculino"});
#line 6
 testRunner.Given("que há um evento de atualizacao de parametros com os seguintes dados", ((string)(null)), table1, "Dado ");
#line 9
 testRunner.When("processar o evento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identificador",
                        "IdentificadorNegocio"});
            table2.AddRow(new string[] {
                        "9B2B0228-4D0D-4C23-8B49-01A698857709",
                        "245a444f-fc39-4ee1"});
#line 10
 testRunner.Then("deve ser criado um evento com os dados abaixo", ((string)(null)), table2, "Então ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periodicidade",
                        "DataNascimento",
                        "Sexo"});
            table3.AddRow(new string[] {
                        "30",
                        "01/01/1980",
                        "Masculino"});
#line 13
 testRunner.And("um historico de cobertura contratada com", ((string)(null)), table3, "E ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
